### ISSUE TITLE
mtree_verify should also accept err

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#1264]
The `mtree_verify` instruction, like the assert instructions, will fail the execution if its [criteria fails](https://github.com/0xPolygonMiden/miden-vm/blob/3a957f7c90176914bda2139f74bff9e5700d59ac/processor/src/operations/crypto_ops.rs#L87-L95). This should also support an error code.

**Comment by Overcastan** [comment]
I'm not sure I understand the purpose of adding an error codes to the `mtree_verify`. 
We decided to add error codes to the assert instructions because they were returning just a `FailedAssertion` error and a cycle number without additional data, so it was difficult to find out what exactly caused an error. 
But in case of `mtree_verify` we have a specific error which contains necessary data about Merkle Tree and a value being checked. 
I think I just missing something, @hackaugusto can you describe in more detail why this is necessary?

**Comment by bobbinth** [comment]
I think the main rationale is that `mtree_verify` acts kind of like an assert instruction. That is, if a Merkle path cannot be verified, the execution fails. These failures can happen in different contexts (e.g., asset is not present in account vault) and it would be helpful to let users specify their own error codes.

**Comment by hackaugusto** [comment]
The motivation for the issue was the usage of `mtree_verify` in miden-base. There are two uses and having an error will make it clearer which one caused an issue (also for other errors)

- authenticate a [note](https://github.com/0xPolygonMiden/miden-base/blob/9a1b1263b1faf661623d74e00878cf51371b1088/miden-lib/asm/miden/kernels/tx/prologue.masm#L564-L565)
- check an [account procedures](https://github.com/0xPolygonMiden/miden-base/blob/9a1b1263b1faf661623d74e00878cf51371b1088/miden-lib/asm/miden/kernels/tx/account.masm#L405-L406)

In general, I think every instruction that can fail should have an error to make debugging easier. My ideal situation would be to have error code to every instruction that can fail. So that when I get a failure in a test, I can just search for the error code and find exactly the instruction that failed.

**Comment by bobbinth** [comment]
Closed by #1328.
