### ISSUE TITLE
Refactor `MastForest` format to put all decorator data at the end

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1489]
_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-vm/pull/1482#discussion_r1751216993_

>Not for this PR, but I wonder if there is a way to refactor this so that all decorator-related data is in one section. This way, if we wanted to drop decorators from the serialized binary, we could just truncate this section without doing any extra processing.

**Comment by yasonk** [comment]
I haven't looked into the serialization code in detail, but just to clarify, the intent is to make the serialization format look like this?

//! The serialization format of MastForest is as follows:
//!
//! (Metadata)
//! - MAGIC
//! - VERSION
//!
//! (lengths)
//! - nodes length (`usize`)
//!
//! (procedure roots)
//! - procedure roots (`Vec<MastNodeId>`)
//!
//! (raw data)
//! - Node data
//! - String table
//!
//! (info structs)
//! - MAST node infos (`Vec<MastNodeInfo>`)
//!
//! (All Decorator data)
//! - decorators length (`usize`)
//! - Decorator data
//! - decorator infos (`Vec<DecoratorInfo>`)
/! 
//! (before enter and after exit decorators)
//! - before enter decorators (`Vec<(MastNodeId, Vec<DecoratorId>)>`)
//! - after exit decorators (`Vec<(MastNodeId, Vec<DecoratorId>)>`)

**Comment by bobbinth** [comment]
I think it is a bit more complicated than that because some decorator data is also stored in the "Node data" section and also strings used by decorators are stored in the "String table" (though, I don't remember this too well now).

But the general idea is correct - we want to move everything decorator-related to the end of the file to make removing decorator data (which is going to be primarily used for debug purposes) as straight-forward as possible.

**Comment by bobbinth** [comment]
For the purposes of uploading the code to the chain, we'd actually need to implement a different serialization format. The main reason is that our current format stores digest of every node. This makes MAST forests fast to deserialize (because we don't need to recompute hashes), but has two drawbacks for the on-chain scenario:

1. Including node digests means adding 32 extra bytes per node. We can avoid this and make things much more compact.
2. The format is "trusted" - i.e., we don't verify that the digests were computed correctly.

**Comment by bobbinth** [comment]
Closed by #1531.
