### ISSUE TITLE
Generated file in repository

### ISSUE THREAD

**Issue by matthiasgoergens** [0xPolygonMiden/miden-vm#620]
The file `stdlib/assets/std.masl` gets generated as part of the build process, but it is checked into the repository.

In general, it's a bad idea to check-in generated files, as they can easily get out of sync but can also easily be re-generated automatically.

I suggest we either remove that file from the repository (or otherwise add a check in the CI/CD to make sure it is up-to-date.)

**Comment by bobbinth** [comment]
This file is imported into Rust source code [here](https://github.com/0xPolygonMiden/miden-vm/blob/next/stdlib/src/lib.rs#L15). I'm curious if it'll still work if we don't commit it. @vlopes11 - what do you think?

**Comment by matthiasgoergens** [comment]
The build system already generates the file before importing it into the Rust source.

It just needed a small fix to create the containing directory, if needed. (Git doesn't track empty directories, so no longer creates the `assets` directory on checkout with the file gone from version control.)

**Comment by vlopes11** [comment]
The reason we have `std.masl` committed is because its build process is deterministic (meaning it shouldn't change as a result of the dependencies tree or rust versions change).

Whenever we have a change in this file, it will be a yellow flag for the PR reviewer, so he can clearly understand if it was expected to have a different behavior on the parsing/compilation process.

This can ofc be achieved via other means, but it might be a heavy maintenance test case to assert the deterministic build of masm files. It is heavy because whenever we want to effectively change the build process, we will have also to update a (likely) huge test case.

Indeed, it is usually best to gitignore build assets, mainly because generated rust files (or some binary asset) might depend on the environment (arch/compiler/libraries/os/etc), and that is something we really don't want here. On the other hand, if we are to remove it, we should introduce a reliable, low maintenance mechanism to shield this case.

wdyt @bobbinth @matthiasgoergens ?

**Comment by matthiasgoergens** [comment]
@vlopes11 Thanks for your explanation.  Alas, yes, at best this is a yellow flag to the reviewer, but our checks don't make sure that the file is up-to-date.

If you want to keep the file in the repository, I suggest you add a check to make sure it's up-to-date.  (Eg by regenerating it, and checking that git doesn't see a difference to what's checked in.)

> The only way for Alice to have a consistent local state is to clean the built stdlib and rebuild again so the changes of Bob will be on her local file.

That would indeed be a problem.  Sorry, I'm a bit slow: could you explain to me how the current system prevents this problem?

**Comment by vlopes11** [comment]
@matthiasgoergens the current system is far from perfect, definitely, but we assume Bob will perform the update on stdlib when he commits his changes. When Alice rebases, she is guaranteed to have the latest build.

We currently have a couple of open issues as the file gets random order of functions and we should probably introduce a mechanism to order them before building the binary file.

One alternative would be to introduce this binary file as a release artifact of next. However, we are under heavy development, so we might have to introduce a mechanism to mitigate a flood of binary files.

An improvement on the system should somehow encompass these cases.

**Comment by bobbinth** [comment]
Closed by #621
