### ISSUE TITLE
Datastructures on Miden

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#626]
I'm opening the issue to start a discussion about which data structure should be included as a library, and what should be their data layout. One possibility is not not have any data structures on the standard library and delegate this to each compiler / programming language, this however has the downside of making it difficult to interoperate on different languages. One initial suggestion is to follow the same layout used by [Solidity](https://docs.soliditylang.org/en/latest/internals/layout_in_storage.html#mappings-and-dynamic-arrays)

**Comment by bobbinth** [comment]
At the `stdlib` level, we are currently planning to have at least 2 data structures defined:

1. A Sparse Merkle tree which maps 256-bit values to 256-bit values (or actually 4 field elements to 4 field elements).
2. A Merkle Mountain Range - which is an append-only accumulator.

We need these two for the rollup. Beyond these, we haven't really defined anything but strings and dynamic arrays could be good future candidates.

One other comment: I think these types of discussions would better go into the Discussions section rather than Issues.

**Comment by hackaugusto** [comment]
> One other comment: I think these types of discussions would better go into the Discussions section rather than Issues.

Closing this is favor of a discussion: https://github.com/0xPolygonMiden/miden-vm/discussions/629
