### ISSUE TITLE
Question: Why is Fmp (free memory pointer) required?

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#773]
The fmp takes up one column in the execution trace and has two associated vm operations. It looks like its used for generating memory addresses for procedure locals? I'm trying to understand why we need the fmp.  Couldn't we just delegate calculation of the memory addresses for procedure locals to the compiler?  This would allows us to free two instruction slots and a trace column.  I'm most likely missing something.  Any information / explanation appreciated.

**Comment by bobbinth** [comment]
The origin of the `fmp` register can be traced to #73. One approach I didn't consider there is for the assembler to compute all local offsets at statically. I now believe that that should be possible because:

1. We don't have recursion and thus, a procedure could not call itself.
2. We inline all procedures by the time we get to a MAST and thus, specific offsets can be applied to each procedure invocation.

There is one thing to consider: if we decide not to inline some procedures in the future, we won't be able to compute offsets statically. One of the reasons why we might not want to inline some procedures would be performance (specifically computing MAST root for a given program).

For example, let's say we have something like an ECDSA signature verification procedure which is probably something like 30K instructions long. Internally, this procedure calls other procedures which rely on local variables. Right now, this procedure always compiles to the same MAST root because all local offsets are relative to the `fmp` register. Thus, once we've built a MAST for this procedure, we don't need to build it again.

However, if we don't have `fmp` register, invoking ECDA procedure in different context would result in different MAST roots (since the inlined offsets would change). So, we'd need to compute MAST root for it each time the procedure is called.

Right now, we don't take a full advantage of this optimization (we frequently recompute MAST roots when it is not needed, and [memoization](https://github.com/0xPolygonMiden/miden-vm/blob/main/processor/src/chiplets/hasher/mod.rs#L80) of computed hashes in the processor is fairly rudimentary), but I think if we get rid of `fmp`, we would not be able to implement these optimizations in the future (and they could be quite significant).

**Comment by frisitano** [comment]
Thanks, that provides a lot of useful context and gives a good foundation for the considerations.  Not being forced to inline procedures is a nice optimisation we probably don't want to give up easily, even if we don't make maximum use of it right now. However, the possibility of freeing two instructions and a trace column is also an attractive proposition.

**Comment by bobbinth** [comment]
Closing this as we will probably keep `fmp` register for now. If needed, we can reopen later.
