### ISSUE TITLE
Change how constraint composition polynomial is constructed

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#877]
In Winterfell, the constraint composition polynomial is constructed using the following formula

$$
\sum_{i=0}^{k-1}  \left(\alpha_i + \beta_i \cdot X^{d_i}\right) \cdot \frac{C_i(X)}{Z_{H_i}(X)}
$$

where:

1. $(\alpha_i, \beta_i)$ is a per-constraint random tuple.
2. $d_i$ is what is called the adjustment factor. This is needed in order to make each of the terms in the above expression have the same degree.
3. $C_i$ is the i-th constraint.
4. $Z_{H_i}$ is the vanishing polynomial on the sub-group $H_i$ where the constraint $C_i$ should hold.

In fact, in Winterfell the constraints are grouped into groups that share the same $d_i$ in order to optimize things.
The use of degree adjustments made sense in earlier versions of the protocol i.e. the original ALI protocol. Moreover, and as noticed [here](https://eprint.iacr.org/2022/1216) in page 16,  we can compute the constraint composition polynomial as 

$$
\mathbb{C}(X) := \sum_{i=0}^{k-1}  \delta_i \cdot \frac{C_i(X)}{Z_{H_i}(X)}
$$

For all sensible choices of security parameters, choosing $\delta_i := \delta^i$ does not degrade soundness as this is usually not the most dominiant part.

Related to this is how $\mathbb{C}(X)$ is divided into `d:= max_degree - 1` many polynomials. [In](https://eprint.iacr.org/2022/1216) page 15, the following decomposition is proposed

$$
\mathbb{C}(X) = h_0(X) + X^{|H|}\cdot h_1(X) + \cdots + X^{(d-1)\cdot|H|}\cdot h_{d-1}(X)
$$

where $|H|$ is the length of the trace.
This decomposition has the advantage of giving a slightly better soundness error as well as avoiding having quotients with denominator  $(X - z^d)$.

**Comment by bobbinth** [comment]
Thank you! This looks great! A couple thoughts/comments:

> Related to this is how $\mathbb{C}(X)$ is divided into `d:= max_degree - 1` many polynomials. [In](https://eprint.iacr.org/2022/1216) page 15, the following decomposition is proposed
> 
> $$
> \mathbb{C}(X) = h_0(X) + X^{|H|}\cdot h_1(X) + \cdots + X^{(d-1)\cdot|H|}\cdot h_{d-1}(X)
> $$
> 
> where $|H|$ is the length of the trace.

To make sure I understood correctly, let's say we have $\mathbb{C}(X) = c_7 \cdot x^7 +  c_6 \cdot x^6 + ... + c_1 \cdot x + c_0$ and  $|H| = 4$. Currently, Winterfell would define $h_0(x)$ and $h_1(x)$ as:

$$
h_0(x) = c_6 \cdot x^6 + c_4 \cdot x^4 + c_2 \cdot x^2 + c_0
$$

$$
h_1(x) = c_7 \cdot x^7 + c_5 \cdot x^5 + c_3 \cdot x^3 + c_1 \cdot x
$$

But with this approach, we would define it as:

$$
h_0(x) = c_3 \cdot x^3 + c_2 \cdot x^2 + c_1 \cdot x^1 + c_0
$$

$$
h_1(x) = c_7 \cdot x^7 + c_6 \cdot x^6 + c_5 \cdot x^5 + c_4 \cdot x^4
$$

Correct?

> we can compute the constraint composition polynomial as 
> 
> $$
> \mathbb{C}(X) := \sum_{i=0}^{k-1}  \delta_i \cdot \frac{C_i(X)}{Z_{H_i}(X)}
> $$

I wonder what the implication of this are for constraint evaluation logic in MASM.

First, I think we still want to process all constraints with the same vanishing polynomial together - i.e., compute sums of numerators (3 separate sums, in our case) and then divide them by the corresponding $Z_{H}(X)$.

Then, I think we have two options for how to compute these sums:

- Option 1: As constraints are evaluated, merge them immediately into the relevant running sum.
- Option 2: After a constraint is evaluated, save the result to memory and once all constraints have been processed in this way, compute their random liner combination.

It is not obvious to me yet which of these would be more efficient - especially since we may be able to introduce a specialized instruction to help with this in both cases.

**Comment by Al-Kindi-0** [comment]
> Correct?

Indeed, instead of even-odd decomposition (in your example) we would have a "segment" decomposition.

> 3 separate sums

Are they, transition, boundary constraints against first row and boundary constraints against last row?
Related to this, there is a cool trick proposed by Dev which in facts reduces the number of randomness used in the following manner:
Suppose for example that we have a one-column execution trace of the Fibonacci sequence. Then the transition constraint is 

$$
C(X) := f(g^2X) - f(gX) - f(X)
$$

with zerofier $\frac{X^N - 1}{(X - g^{N-1})(X - g^{N-2})}$.
The boundary constraints are encoded as $\frac{f(X) - 1}{X - 1}$, $\frac{f(X) - 1}{X - g}$ and $\frac{f(X) - A}{X - g^{N-1}}$ where $A$ is the claimed Fibonacci number.

The integrity of execution is then reduced to the existence of a polynomial $Q$ such that

$$
\alpha_0 \frac{C(X)}{\frac{X^N - 1}{(X - g^{N-1})(X - g^{N-2})}} + \alpha_1 \frac{f(X) - 1}{X - 1} + \alpha_2 \frac{f(X) - 1}{X - g} + \alpha_3 \frac{f(X) - A}{X - g^{N-1}} = Q(X)
$$

Now multiplying both sides of the equality with $X^N - 1$ we get 

$$
\alpha_0 C(X)(X - g^{N-1})(X - g^{N-2}) + \alpha_1 L_0(X)\cdot(f(X) - 1) + \alpha_2 L_1(X)\cdot(f(X) - 1) + \alpha_3 L_{N-1}(X)(f(X) - A) = Q(X) \cdot (X^N - 1)
$$

where $L_i(X) := \frac{X^N - 1}{X - g^i}$ is the i-th Lagrange basis polynomial (up to constants) playing the role of a selector polynomial.
Now, by the properties of Lagrange basis polynomials, at most on of the last three terms can be non-zero and thus the above can be simplified to 

$$
\alpha_0 C(X)(X - g^{N-1})(X - g^{N-2}) + \alpha_1 \left( L_0(X)\cdot(f(X) - 1) + L_1(X)\cdot(f(X) - 1) +  L_{N-1}(X)(f(X) - A) \right) = Q(X) \cdot (X^N - 1)
$$

with a different $Q$ of course.

This is a cool trick that allows us to reduce the number of random values used for merging boundary constraints. Although its benefits are questionable in our setting, it is good to document it here.

> It is not obvious to me yet which of these would be more efficient - especially since we may be able to introduce a specialized instruction to help with this in both cases.

One thing that could tip the scale in favor of the second option is the fact that when using a single power of a single random value we can use Horner rule of evaluation. The fact that we have three sums complicates things a bit but shouldn't be too difficult to overcome, I believe.

**Comment by Al-Kindi-0** [comment]
This has now being implemented in Winterfell.
